import { createContext, useContext } from 'react';

// One syllabus, whichever document it came from. The chart, the stage nav, the block page and
// the event hub read the syllabus they are showing through this shape and never touch a
// document themselves, so the same components render Delta Primary and a syllabus someone
// generated by uploading a JPPT. Both are now documents on the server: Delta is the one with
// id `delta-primary`, loaded by DiscussData before anything else renders.
//
// Discuss item pages are shared by every syllabus: an item has one canonical URL, however many
// syllabi brief it. Only Delta carries ?from= event context onto them, because the item page's
// context strip reads Delta's events.

export const DISCUSS_BASE = '/tw4/discuss';
export const DELTA_ID = 'delta-primary';

function index(rows) {
  const out = {};
  rows.forEach((r) => { out[r.id.toUpperCase()] = r; });
  return out;
}

// React key for an item row. Neither half is unique on its own: all 31 EP rows share one
// href, and FAM3103 lists "crosswind takeoff" and "crosswind landings" as two JPPT items
// resolving to one page. The label is what separates them, and labels are unique within an
// event, so the pair always is.
export function rowKey(row) {
  return `${row.slug || row.href || 'none'}|${row.label}`;
}

// Link rows shown under one name wherever they appear, whatever the JPPT wording. The JPPT
// writes the EP rows six ways ("any EP", "emergency procedures", "any critical action
// emergency procedures", …) and all of them open the same page, so on screen they are one
// item. `searchable: false` keeps them out of the search box, which lists pages to read.
const LINK_ROWS = {
  '/tw4/eps-limits': { name: 'Any critical action emergency procedure', searchable: false },
};

// What a row is called on its event's list: the row's own `label`, which starts as the JPPT's
// wording and is editable. Several rows may point at one page and each keeps its own name —
// FAM1301 lists ATF, ATS, CTS and MIF, all of which open one page, and a list printing that
// page's title four times says nothing about what is briefed. Search results, hatnotes and
// See also still name the page by its `title`, which is the page's name rather than an
// event's name for it.
export function rowName(row) {
  const link = row.href && LINK_ROWS[row.href];
  return link ? link.name : row.label;
}

export function rowSearchable(row) {
  const link = row.href && LINK_ROWS[row.href];
  return !link || link.searchable !== false;
}

export function buildSyllabus({
  id, name, base, source, rev = null, builtIn = false, record = null,
  aircraft = '', school = '',
  stages, blocks, events, flow, isBriefed,
}) {
  const blockIndex = index(blocks);
  const stageIndex = index(stages);
  const eventIndex = index(events);

  const syllabusEvents = blocks.flatMap((block) =>
    block.events.map((e) => ({
      id: e.id,
      title: e.title || block.title,
      note: e.note || null,
      block: block.id,
      stage: block.stage,
    }))
  );
  const syllabusIndex = index(syllabusEvents);

  const getBlock = (bid) => (bid && blockIndex[bid.toUpperCase()]) || null;
  const syllabusEvent = (eid) => (eid && syllabusIndex[eid.toUpperCase()]) || null;
  const blockOf = (eid) => {
    const e = syllabusEvent(eid);
    return e ? blockIndex[e.block.toUpperCase()] : null;
  };

  // Accepts a block id, an event id, or a block row.
  const hasDiscussItems = (idOrBlock) => {
    if (!idOrBlock) return false;
    const block = typeof idOrBlock === 'string'
      ? (getBlock(idOrBlock) || blockOf(idOrBlock))
      : idOrBlock;
    return !!block && isBriefed(block);
  };

  const blocksIn = (sid) => blocks.filter((b) => b.stage === (sid && sid.toUpperCase()));
  const briefedBlocksIn = (sid) => blocksIn(sid).filter(hasDiscussItems);

  // Content for an event: only events in a briefed block have any.
  const getEvent = (eid) => {
    const e = eid && eventIndex[eid.toUpperCase()];
    return e && hasDiscussItems(e.id) ? e : null;
  };

  // Where an item row points. An `href` row goes wherever it says; a slug row goes to its
  // canonical page, carrying event context (Delta only) so the page can offer prev/next
  // through the list.
  const rowTo = (row, eventId) => {
    if (!row) return null;
    if (row.href) return row.href;
    if (!row.slug) return null;
    return `${DISCUSS_BASE}/${row.slug}${builtIn && eventId ? `?from=${eventId}` : ''}`;
  };

  return {
    id,
    name,
    base,
    source,
    rev,
    builtIn,
    record,
    // The aircraft and the school the syllabus is for; every page it links should match.
    aircraft,
    school,
    flow,
    stages,
    blocks,
    events,
    getStage: (sid) => (sid && stageIndex[sid.toUpperCase()]) || null,
    getBlock,
    syllabusEvent,
    blockOf,
    blocksIn,
    hasDiscussItems,
    briefedBlocksIn,
    // Every stage with something in it to open, in registry order.
    navStages: () => stages.filter((s) => briefedBlocksIn(s.id).length > 0),
    briefedEvents: () => syllabusEvents.filter((e) => hasDiscussItems(e.id)),
    getEvent,
    eventPath: (eid) => `${base}/e/${eid}`,
    blockPath: (bid) => `${base}/b/${bid}`,
    stagePath: (sid) => `${base}#${sid}`,
    rowTo,
    // Where `slug` sits in `event`'s list, and what flanks it. Drives the ?from= context
    // strip. Where one page answers two of an event's JPPT items, the first occurrence is the
    // one reported — a page has one position in a list, however many labels point at it.
    positionIn: (event, slug) => {
      if (!event) return null;
      const at = event.items.findIndex((i) => i.slug === slug);
      if (at === -1) return null;
      return {
        index: at,
        total: event.items.length,
        prev: at > 0 ? event.items[at - 1] : null,
        next: at < event.items.length - 1 ? event.items[at + 1] : null,
      };
    },
    // Every event that lists this item, so an item page can show where it is briefed.
    eventsListing: (slug) => events.filter((e) => e.items.some((i) => i.slug === slug)),
  };
}

// A published syllabus document (see jppt/parseJppt.js) as a syllabus.
//
// `matcher` re-matches the rows an upload could not link, so a page written after the upload
// is linked without anyone republishing. Delta passes none: its label-only rows are
// deliberate, and fuzzy-matching them would silently relink pages.
export function fromDoc(record, { builtIn = false, matcher = null } = {}) {
  const { doc } = record;
  const events = (doc.events || []).map((e) => ({
    ...e,
    items: (e.items || []).map((row) => (
      // `noPage` is a decision that this item wants no page, so it is not re-matched: the
      // re-match exists to catch up with pages written later, not to overrule the reader.
      row.slug || row.href || row.noPage || !matcher ? row : { ...row, ...matcher.matchLabel(row.label) }
    )),
  }));
  return buildSyllabus({
    id: record.id,
    name: record.name || doc.name,
    base: builtIn ? DISCUSS_BASE : `${DISCUSS_BASE}/s/${record.id}`,
    source: doc.source && doc.source.citation,
    rev: record.rev,
    builtIn,
    record,
    aircraft: doc.aircraft || record.aircraft || '',
    school: doc.school || record.school || '',
    stages: doc.stages || [],
    blocks: doc.blocks || [],
    events,
    flow: doc.flow,
    isBriefed: (block) => !!block.briefed,
  });
}

export const SyllabusContext = createContext(null);

export function useSyllabus() {
  return useContext(SyllabusContext);
}
