// Generated by tools/about-stats.js — do not edit.
//
// What each school's syllabi and briefs add up to, as of the last run. The About pages and the
// landing page paint from this at once and then correct it from the server, so these are a
// starting point rather than the truth; see the header of that tool.

export const SERVER_STATS = {
  "NIFE": {
    "weeks": [
      {
        "weeks": 8,
        "label": "Calendar Weeks",
        "names": [
          "NIFE Syllabus"
        ]
      }
    ],
    "syllabi": [
      {
        "id": "nife-flight",
        "name": "NIFE Syllabus",
        "discussItems": 43
      }
    ],
    "briefs": [
      {
        "aircraft": "C172",
        "words": 651
      }
    ]
  },
  "Primary": {
    "weeks": [
      {
        "weeks": 28,
        "label": "Production Weeks",
        "names": [
          "Delta Syllabus",
          "Echo Syllabus"
        ]
      }
    ],
    "syllabi": [
      {
        "id": "delta-primary",
        "name": "Delta Syllabus",
        "discussItems": 475
      },
      {
        "id": "echo-syllabus-primary-76ae",
        "name": "Echo Syllabus",
        "discussItems": 478
      }
    ],
    "briefs": [
      {
        "aircraft": "T-6B",
        "words": 1908
      },
      {
        "aircraft": "T-6B",
        "words": 1959
      }
    ]
  },
  "Advanced": {
    "weeks": [
      {
        "weeks": 19,
        "label": "Production Weeks",
        "names": [
          "E-2D"
        ]
      },
      {
        "weeks": 23,
        "label": "Production Weeks",
        "names": [
          "P-8",
          "E-6",
          "C-130",
          "USCG",
          "Tilt-Rotor"
        ]
      }
    ],
    "syllabi": [
      {
        "id": "t44c-e2d",
        "name": "T-44C E-2D Intermediate",
        "discussItems": 495
      },
      {
        "id": "t44c-p8",
        "name": "T-44C P-8 Advanced",
        "discussItems": 628
      }
    ],
    "briefs": []
  }
};
