#!/usr/bin/env node
//
// The numbers the landing page and the About pages show for each school, read off the mirror
// and written to src/components/about/serverStats.js.
//
//   node tools/about-stats.js
//   node tools/about-stats.js --mirror=http://localhost:8787/mirror --dry-run
//
// WHY A SNAPSHOT. These figures come from documents on the server, so the pages used to fetch
// every syllabus and every brief — about a third of a megabyte — to put six numbers on screen,
// and showed a dash until it landed. They change only when somebody publishes. So they are
// written here, painted from the file at once, and the read still runs behind them and corrects
// anything a publish has changed since: the page is never blank and never wrong for long.
//
// RE-RUN IT AFTER PUBLISHING. A stale snapshot is corrected on the reader's next load, so
// nothing is broken by forgetting; the numbers just flicker once, which is what this exists to
// avoid. The deploy already needs a push, so it fits where a publish already goes.
//
// The counting is NOT repeated here. `src/components/about/stats.js` is loaded through
// tools/lib/loadSrc.js and its own functions are used, so a snapshot figure and a fetched one
// cannot disagree.

const fs = require('fs');
const path = require('path');
const { loadSrc } = require('./lib/loadSrc');

const argv = process.argv.slice(2);
const flag = (n) => argv.includes(`--${n}`);
const value = (n) => {
  const hit = argv.find((a) => a.startsWith(`--${n}=`));
  return hit ? hit.slice(n.length + 3) : null;
};

const MIRROR = value('mirror') || process.env.REACT_APP_DISCUSS_MIRROR
  || 'https://pinksheetmafia-discuss.s3.us-east-2.amazonaws.com';
const OUT = path.join(__dirname, '..', 'src', 'components', 'about', 'serverStats.js');

const SRC = path.join(__dirname, '..', 'src', 'components');
const { weekGroups, syllabusRows, briefRows } = loadSrc(path.join(SRC, 'about', 'stats.js'));
const { PROGRAMS, isSchool } = loadSrc(path.join(SRC, 'programs.js'));

async function getJson(url) {
  const res = await fetch(url, { cache: 'no-cache' });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res.json();
}

const index = (name) => getJson(`${MIRROR}/${name}/index.json`).catch(() => null);

// A brief's file is keyed by its lower-cased id, as briefApi reads it.
async function records(name, rows, id) {
  const out = await Promise.all(rows.map((r) => getJson(`${MIRROR}/${name}/${id(r)}.json`).catch(() => null)));
  return out.filter(Boolean);
}

async function main() {
  const [syllabi, briefs] = await Promise.all([index('syllabi'), index('briefs')]);
  const stats = {};

  for (const program of PROGRAMS) {
    const school = program.label;
    const mine = ((syllabi && syllabi.syllabi) || []).filter((s) => isSchool(s, school));
    const briefRowsFor = ((briefs && briefs.briefs) || []).filter((b) => isSchool(b, school));
    // eslint-disable-next-line no-await-in-loop
    const [syllabusDocs, briefDocs] = await Promise.all([
      records('syllabi', mine, (r) => r.id),
      records('briefs', briefRowsFor, (r) => String(r.id).toLowerCase()),
    ]);
    const entry = {
      weeks: weekGroups(syllabusDocs),
      syllabi: syllabusRows(syllabusDocs),
      briefs: briefRows(briefDocs),
    };
    // A school with nothing published carries nothing, so its panel shows a dash and says so
    // rather than claiming a confident zero.
    if (entry.weeks.length || entry.syllabi.length || entry.briefs.length) stats[school] = entry;
  }

  const body = `// Generated by tools/about-stats.js — do not edit.
//
// What each school's syllabi and briefs add up to, as of the last run. The About pages and the
// landing page paint from this at once and then correct it from the server, so these are a
// starting point rather than the truth; see the header of that tool.

export const SERVER_STATS = ${JSON.stringify(stats, null, 2)};
`;

  if (flag('dry-run')) {
    console.log(body);
    return;
  }
  fs.writeFileSync(OUT, body);
  const names = Object.keys(stats);
  console.log(`${path.relative(process.cwd(), OUT)}: ${names.length ? names.join(', ') : 'nothing published'}`);
  names.forEach((s) => console.log(`  ${s}: ${stats[s].syllabi.length} syllabi, ${stats[s].briefs.length} briefs`));
}

main().catch((err) => {
  console.error(err.message || err);
  process.exit(1);
});
