#!/usr/bin/env node
//
// The numbers the landing page and the About pages show for each school, read off the mirror
// and written to src/components/about/serverStats.js.
//
//   node tools/about-stats.js
//   node tools/about-stats.js --mirror=http://localhost:8787/mirror --dry-run
//
//   --force   write an empty snapshot over one that has figures in it, which it otherwise refuses
//
// WHY A SNAPSHOT. These figures come from documents on the server, so the pages used to fetch
// every syllabus and every brief — about a third of a megabyte — to put six numbers on screen,
// and showed a dash until it landed. They change only when somebody publishes. So they are
// written here, painted from the file at once, and the read still runs behind them and corrects
// anything a publish has changed since: the page is never blank and never wrong for long.
//
// RE-RUN IT AFTER PUBLISHING. A stale snapshot is corrected on the reader's next load, so
// nothing is broken by forgetting; the numbers just flicker once, which is what this exists to
// avoid. The deploy already needs a push, so it fits where a publish already goes.
//
// The counting is NOT repeated here. `src/components/about/stats.js` is loaded through
// tools/lib/loadSrc.js and its own functions are used, so a snapshot figure and a fetched one
// cannot disagree.

const fs = require('fs');
const path = require('path');
const { loadSrc } = require('./lib/loadSrc');
const { MIRROR_URL } = require('./lib/cli');

const argv = process.argv.slice(2);
const flag = (n) => argv.includes(`--${n}`);
const value = (n) => {
  const hit = argv.find((a) => a.startsWith(`--${n}=`));
  return hit ? hit.slice(n.length + 3) : null;
};

const MIRROR = value('mirror') || process.env.REACT_APP_DISCUSS_MIRROR || MIRROR_URL;
const OUT = path.join(__dirname, '..', 'src', 'components', 'about', 'serverStats.js');

const SRC = path.join(__dirname, '..', 'src', 'components');
const { weekGroups, syllabusRows, briefRows, questionCount } = loadSrc(path.join(SRC, 'about', 'stats.js'));
const { PROGRAMS, isSchool, schoolOf } = loadSrc(path.join(SRC, 'programs.js'));

// Only a 404 means "nothing published", and then only where `missingOk` says it may. Any
// other failure stops the run: a snapshot written from a half-read mirror would paint wrong
// figures until the reader's own fetch corrected them, which is what the file exists to avoid.
async function getJson(url, { missingOk = false } = {}) {
  const res = await fetch(url, { cache: 'no-cache' }).catch((err) => {
    throw new Error(`${err.message} ${url}`);
  });
  if (missingOk && res.status === 404) return null;
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res.json();
}

const index = (name) => getJson(`${MIRROR}/${name}/index.json`, { missingOk: true });

// A brief's file is keyed by its lower-cased id, as briefApi reads it. Every record an index
// lists must be there.
const records = (name, rows, id) => Promise.all(rows.map((r) => getJson(`${MIRROR}/${name}/${id(r)}.json`)));

async function main() {
  const [syllabi, briefs] = await Promise.all([index('syllabi'), index('briefs')]);
  const stats = {};

  for (const program of PROGRAMS) {
    // The word the school's documents are filed under: both Advanced programs are labelled
    // Advanced, and the T-54A's syllabi and briefs carry its own school, T-54A.
    const school = schoolOf(program);
    const mine = ((syllabi && syllabi.syllabi) || []).filter((s) => isSchool(s, school));
    const briefRowsFor = ((briefs && briefs.briefs) || []).filter((b) => isSchool(b, school));
    // eslint-disable-next-line no-await-in-loop
    const [syllabusDocs, briefDocs] = await Promise.all([
      records('syllabi', mine, (r) => r.id),
      records('briefs', briefRowsFor, (r) => String(r.id).toLowerCase()),
    ]);
    const entry = {
      weeks: weekGroups(syllabusDocs),
      syllabi: syllabusRows(syllabusDocs),
      briefs: briefRows(briefDocs),
    };
    // A school with nothing published carries nothing, so its panel shows a dash and says so
    // rather than claiming a confident zero.
    if (entry.weeks.length || entry.syllabi.length || entry.briefs.length) stats[school] = entry;
  }

  // The Questions tab's live count, which only NIFE has.
  const [approved, sections] = await Promise.all([
    getJson(`${MIRROR}/questions/nife/approved.json`, { missingOk: true }),
    getJson(`${MIRROR}/questions/nife/sections.json`, { missingOk: true }),
  ]);
  const questions = questionCount(approved && approved.questions, sections && sections.doc);
  if (questions != null) stats.NIFE = { ...(stats.NIFE || {}), questions };

  const body = `// Generated by tools/about-stats.js — do not edit.
//
// What each school's syllabi, briefs and questions add up to, as of the last run. The About
// pages and the landing page paint from this at once and then correct it from the server, so
// these are a starting point rather than the truth; see the header of that tool.

export const SERVER_STATS = ${JSON.stringify(stats, null, 2)};
`;

  if (flag('dry-run')) {
    console.log(body);
    return;
  }
  const names = Object.keys(stats);
  // An empty snapshot over a full one is far likelier a wrong --mirror than a site with
  // nothing on it.
  const before = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (!names.length && !/SERVER_STATS = \{\s*\};/.test(before) && before && !flag('force')) {
    throw new Error(`nothing published at ${MIRROR}; ${path.relative(process.cwd(), OUT)} left as it is (--force to empty it)`);
  }
  fs.writeFileSync(OUT, body);
  console.log(`${path.relative(process.cwd(), OUT)}: ${names.length ? names.join(', ') : 'nothing published'}`);
  names.forEach((s) => console.log(`  ${s}: ${(stats[s].syllabi || []).length} syllabi, ${(stats[s].briefs || []).length} briefs`
    + (stats[s].questions != null ? `, ${stats[s].questions} questions` : '')));
}

main().catch((err) => {
  console.error(err.message || err);
  process.exit(1);
});
